Create method of request
hidehiro98/airflow_beta pull request #16
Opened 2017-06-14 05:32 UTC by hidehiro98

@db0sch 🙏

2017-06-14 07:10 UTC, db0sch requested changes

2017-06-14 07:10 UTC, db0sch commented on app/models/request.rb
> +      if receiver.status == 'accepted'
what about `receivers.all?(&:accepted?)`
if it returns true, then you can change the status.

something like this:
 `accepted! if receivers.all?(&:accepted?)`

2017-06-14 07:10 UTC, db0sch commented on app/views/requests/received_requests/_received_request_card.html.erb
> +      <%= link_to 'More', request, class: "card-left-bottom-button btn btn-primary btn-block" %>
you need to pass a real path, no?

2017-06-16 04:17 UTC, hidehiro98 commented on app/views/requests/received_requests/_received_request_card.html.erb
> +      <%= link_to 'More', request, class: "card-left-bottom-button btn btn-primary btn-block" %>
Yes, and it works with only instance (without request_path).
I found this in this lecture slide, and checked with the rails document.
https://karr.lewagon.org/lectures/rails/ajax-in-rails#/2/7

```
link_to "Profile", profile_path(@profile)
# => <a href="/profiles/1">Profile</a>
or the even pithier

link_to "Profile", @profile
# => <a href="/profiles/1">Profile</a>
```
http://api.rubyonrails.org/v5.1/classes/ActionView/Helpers/UrlHelper.html

2017-06-16 06:26 UTC, db0sch approved these changes

2017-06-16 06:28 UTC, merged