Add some functions
hidehiro98/airflow_beta pull request #17
Opened 2017-06-19 12:00 UTC by hidehiro98

@db0sch 🙏

2017-06-20 02:25 UTC, db0sch requested changes

2017-06-20 02:25 UTC, db0sch commented on app/controllers/requests/received_requests_controller.rb
> +    @requests = current_user.received_requests.sort_by { |request| request.duedate }
you should use a scope. cf active record query documentation

2017-06-20 02:25 UTC, db0sch commented on app/controllers/requests/sent_requests_controller.rb
> +    @requests = current_user.requests.sort_by { |request| request.duedate }
same here.

2017-06-20 02:25 UTC, db0sch commented on app/models/request.rb
> +  enum open_closed: { open: 0, closed: 1 }
i think, you can add that to the status enum.
`{ pending: 0, accepted: 1, rejected: 2, commented: 3, closed: 4 }`

0, 1, 2, and 3 are open.
4 is closed.

2017-06-20 02:25 UTC, db0sch commented on db/migrate/20170619114606_add_open_closed_to_request.rb
> +    add_column :requests, :open_closed, :integer, default: 0
no need. cf above.

2017-06-20 04:59 UTC, hidehiro98 commented on app/controllers/requests/received_requests_controller.rb
> +    @requests = current_user.received_requests.sort_by { |request| request.duedate }
I found it. thank you!
http://guides.rubyonrails.org/active_record_querying.html#ordering

2017-06-20 05:36 UTC, hidehiro98 commented on app/models/request.rb
> +  enum open_closed: { open: 0, closed: 1 }
I thought about that, but if I did so, user cannot use open/closed and pending/accepted... at the same time as a search query.
I think it is not convenient, how do you think?

2017-06-20 13:03 UTC, db0sch commented on app/models/request.rb
> +  enum open_closed: { open: 0, closed: 1 }
```
enum status: { pending: 0, accepted: 1, rejected: 2, commented: 3, canceled: 4 }
```
with

```
scope :open, -> { where(status: [;pending, :commented] }
scope :closed, -> { where(status: [:accepted, :rejected, :canceled] }
```

2017-06-21 05:27 UTC, hidehiro98 commented on app/models/request.rb
> +  enum open_closed: { open: 0, closed: 1 }
It means when request accepted, it's automatically closed, right?
Before, I thought user close requests by click 'close' button, but I think automatic is better.
So I also changed the tabs 'Open / To close / Closed' to 'Open / Closed'

2017-06-23 02:42 UTC, db0sch approved these changes
LGTM

2017-06-23 02:43 UTC, merged

2017-06-23 02:52 UTC, hidehiro98 commented
ありがとう！

2017-06-23 05:40 UTC, db0sch commented
:fist_oncoming: